#ifndef RANK_PRELUDE_HANDLER_STATE_H
#define RANK_PRELUDE_HANDLER_STATE_H

enum class HandlerState {
    READY,
    PRESENTING,
    AUCTION_BIDDING,
    AUCTION_WAITING,
    ASSESSING,
    PRE_RESERVED,
    RESERVED,
    REPLENISHING,
    CLOSED
};

#endif  // RANK_PRELUDE_HANDLER_STATE_H
