#ifndef RANK_PRELUDE_RESERVATION_STATE_H
#define RANK_PRELUDE_RESERVATION_STATE_H

enum class ReservationState { CREATED, VIRTUALLY_PRE_RESERVED, PRE_RESERVED, RESERVED, CLEARED };

#endif  // RANK_PRELUDE_RESERVATION_STATE_H
